---
version: 2.1

orbs:
  prometheus: prometheus/prometheus@0.11.0

executors:
  # This must match .promu.yml.
  golang:
    docker:
    - image: circleci/golang:1.16

jobs:
  test:
    executor: golang

    steps:
    - checkout
    - run: go mod download
    - run: make promu
    - run: make style lint unused test build
    - run: rm -v smokeping_prober

workflows:
  version: 2
  smokeping_prober:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - prometheus/build:
        name: build
        filters:
          tags:
            only: /.*/
    - prometheus/publish_master:
        docker_hub_organization: superque
        quay_io_organization: superq
        requires:
        - test
        - build
        filters:
          branches:
            only: master
    - prometheus/publish_release:
        docker_hub_organization: superque
        quay_io_organization: superq
        requires:
        - test
        - build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
